# Generated by Django 5.1.1 on 2025-12-01 08:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Fall 2024', max_length=50, unique=True)),
                ('semester_type', models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer'), ('winter', 'Winter')], max_length=10)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'ordering': ['-year', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Course code (e.g., CS101)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Full course name', max_length=200)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('credits', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_teaching', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Dataset name', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='performance.course')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets_uploaded', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='performance.semester')),
            ],
            options={
                'verbose_name': 'Dataset',
                'verbose_name_plural': 'Datasets',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'course', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Group name (e.g., Group A)', max_length=50)),
                ('max_students', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='performance.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='performance.semester')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ['course', 'name'],
                'unique_together': {('course', 'semester', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text='Student ID number', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['student_id'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_text', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='performance.course')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_recommendations', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='performance.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='performance.student')),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'ordering': ['-created_at', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('records_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='performance.course')),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='performance.dataset')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='performance.semester')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upload History',
                'verbose_name_plural': 'Upload Histories',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz1', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Quiz 1 score (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('quiz2', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Quiz 2 score (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('assignment', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Assignment score (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('attendance', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Attendance percentage (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mid_semester', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Mid-semester exam score (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('final_exam', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Final exam score (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('other_total', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Sum of quiz1 + quiz2 + assignment + attendance', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(400)])),
                ('score', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Final weighted score (30% mid + 40% final + 30% other)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D', 'D'), ('F', 'F')], max_length=3)),
                ('status', models.CharField(blank=True, choices=[('PASS', 'Pass'), ('PROBATION', 'Probation'), ('FAIL', 'Fail')], help_text='PASS (≥50), PROBATION (40-49), FAIL (<40)', max_length=20)),
                ('performance_status', models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], help_text='Excellent (≥85), Good (70-84), Average (50-69), Poor (<50)', max_length=20)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('ml_predicted_pass', models.BooleanField(blank=True, help_text='ML prediction: True=Pass, False=Fail', null=True)),
                ('ml_confidence', models.DecimalField(blank=True, decimal_places=2, help_text='ML prediction confidence (0-100%)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ml_prediction_label', models.CharField(blank=True, help_text='Pass or Fail label from ML model', max_length=10)),
                ('risk_level', models.CharField(choices=[('CRITICAL', 'Critical Risk'), ('HIGH', 'High Risk'), ('MEDIUM', 'Medium Risk'), ('LOW', 'Low Risk'), ('NONE', 'No Risk'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='Automated risk assessment based on ML + rules', max_length=20)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, help_text='Composite risk score (0=no risk, 100=critical risk)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('performance_trend', models.CharField(choices=[('IMPROVING', 'Improving'), ('STABLE', 'Stable'), ('DECLINING', 'Declining'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='Predicted trend based on historical data', max_length=20)),
                ('predicted_final_score', models.DecimalField(blank=True, decimal_places=2, help_text='ML-predicted final score based on current performance', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('needs_intervention', models.BooleanField(default=False, help_text='Flagged for immediate intervention')),
                ('intervention_priority', models.IntegerField(blank=True, help_text='Intervention priority (1=highest, 10=lowest)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('prob_fail', models.DecimalField(blank=True, decimal_places=2, help_text='Probability of failure (0-100%)', max_digits=5, null=True)),
                ('prob_pass', models.DecimalField(blank=True, decimal_places=2, help_text='Probability of passing (0-100%)', max_digits=5, null=True)),
                ('ml_model_version', models.CharField(blank=True, help_text='Version of ML model used for prediction', max_length=50)),
                ('ml_predicted_at', models.DateTimeField(blank=True, help_text='Timestamp when ML prediction was made', null=True)),
                ('ml_features_json', models.JSONField(blank=True, help_text='JSON dump of features used for prediction', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='performance.course')),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='performance.dataset')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performances', to='performance.group')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='performance.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='performance.student')),
            ],
            options={
                'verbose_name': 'Performance Record',
                'verbose_name_plural': 'Performance Records',
                'ordering': ['-semester', 'course', '-score'],
                'indexes': [models.Index(fields=['course', 'semester'], name='performance_course__6da940_idx'), models.Index(fields=['student', 'semester'], name='performance_student_3e96d0_idx'), models.Index(fields=['status'], name='performance_status_5be260_idx'), models.Index(fields=['performance_status'], name='performance_perform_65b0a2_idx'), models.Index(fields=['dataset'], name='performance_dataset_5984fb_idx'), models.Index(fields=['risk_level'], name='performance_risk_le_27eb00_idx'), models.Index(fields=['ml_predicted_pass'], name='performance_ml_pred_84037d_idx'), models.Index(fields=['needs_intervention'], name='performance_needs_i_728862_idx')],
                'unique_together': {('student', 'course', 'semester', 'dataset')},
            },
        ),
    ]
