# Generated by Django 5.2.8 on 2025-11-22 16:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_dataset_alter_performance_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_courses', models.IntegerField(default=0)),
                ('total_credits', models.IntegerField(default=0)),
                ('gpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Semester Enrollment',
                'verbose_name_plural': 'Semester Enrollments',
                'ordering': ['-semester', 'student'],
            },
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['-start_date'], 'verbose_name': 'Semester', 'verbose_name_plural': 'Semesters'},
        ),
        migrations.RemoveIndex(
            model_name='performance',
            name='performance_dataset_5984fb_idx',
        ),
        migrations.AlterUniqueTogether(
            name='dataset',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together={('student', 'course', 'semester')},
        ),
        migrations.RemoveField(
            model_name='uploadhistory',
            name='dataset',
        ),
        migrations.AddField(
            model_name='dataset',
            name='record_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=3, help_text='Course credits (1-6)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='performance',
            name='grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D', 'D'), ('F', 'F')], max_length=3),
        ),
        migrations.AlterField(
            model_name='performance',
            name='performance_status',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_type',
            field=models.CharField(blank=True, choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='semesterenrollment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='performance.semester'),
        ),
        migrations.AddField(
            model_name='semesterenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_enrollments', to='performance.student'),
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='course',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='uploaded_by',
        ),
        migrations.AlterUniqueTogether(
            name='semesterenrollment',
            unique_together={('student', 'semester')},
        ),
    ]
