# Generated by Django 5.2.8 on 2025-11-22 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_add_dataset_semester'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # STEP 1: Remove old model and fields first
        migrations.AlterUniqueTogether(
            name='semesterenrollment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='semesterenrollment',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='semesterenrollment',
            name='student',
        ),
        migrations.DeleteModel(
            name='SemesterEnrollment',
        ),
        
        # STEP 2: Clear unique_together constraints that will be modified
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='dataset',
            unique_together=set(),  # Clear it first
        ),
        
        # STEP 3: Add new fields
        migrations.AddField(
            model_name='dataset',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='performance.course'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='performance.semester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performance',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='performance.dataset'),
        ),
        migrations.AddField(
            model_name='performance',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='performance.dataset'),
        ),
        
        # STEP 4: Modify existing fields
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['-year', '-start_date'], 'verbose_name': 'Semester', 'verbose_name_plural': 'Semesters'},
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='performance',
            name='grade',
            field=models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D', 'D'), ('F', 'F')], max_length=3),
        ),
        migrations.AlterField(
            model_name='performance',
            name='performance_status',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_type',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='file_path',
            field=models.FileField(default=1, upload_to='uploads/%Y/%m/'),
            preserve_default=False,
        ),
        
        # STEP 5: Add unique_together constraints AFTER fields exist
        migrations.AlterUniqueTogether(
            name='dataset',
            unique_together={('name', 'semester', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together={('student', 'course', 'semester', 'dataset')},
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('semester_type', 'year')},
        ),
        
        # STEP 6: Add indexes
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['dataset'], name='performance_dataset_5984fb_idx'),
        ),
        
        # STEP 7: Remove fields last
        migrations.RemoveField(
            model_name='dataset',
            name='record_count',
        ),
    ]