# Generated by Django 5.1.1 on 2025-11-28 22:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0005_alter_semesterenrollment_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('office_location', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.AddField(
            model_name='performance',
            name='assignment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Assignment score (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='performance',
            name='attendance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Attendance score (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='performance',
            name='final_exam',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Final exam score (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='performance',
            name='mid_semester',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Mid-semester exam score (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='performance',
            name='other_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Sum of quiz1 + quiz2 + assignment + attendance', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(400)]),
        ),
        migrations.AddField(
            model_name='performance',
            name='quiz1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Quiz 1 score (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='performance',
            name='quiz2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Quiz 2 score (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='performance',
            name='status',
            field=models.CharField(blank=True, choices=[('PASS', 'Pass'), ('PROBATION', 'Probation'), ('FAIL', 'Fail')], help_text='PASS (≥50), PROBATION (40-49), FAIL (<40)', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='grade_distribution',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='skipped_8_course_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='skipped_duplicates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='status_distribution',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D', 'D'), ('F', 'F')], max_length=3),
        ),
        migrations.AlterField(
            model_name='performance',
            name='performance_status',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], help_text='Excellent (≥85), Good (70-84), Average (50-69), Poor (<50)', max_length=20),
        ),
        migrations.AlterField(
            model_name='performance',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Final weighted score (30% mid + 40% final + 30% other)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['status'], name='performance_status_5be260_idx'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
